var _fujswc_protocol = 'https:/'+'/';
var _fujswc_url = _fujswc_protocol + 'dyn-img.com/i';
var _fujswc_ac = 'dlmotor';
function _fujswclib_urlEncode(g,l){var f,k,h,w;f="";for(k=0;k<g.length;++k)h=g.charCodeAt(k),15>=h?f+="%0"+h.toString(16):47===h?f+=l||"%2f":16<=h&&44>=h||58<=h&&64>=h||91<=h&&96>=h||123<=h&&127>=h?f+="%"+h.toString(16):55296<=h&&56320>h&&56320<=(w=g.charCodeAt(k+1))&&57344>w?(f+=encodeURIComponent(String.fromCharCode(h)+String.fromCharCode(w)),++k):f=128<=h?f+encodeURIComponent(String.fromCharCode(h)):f+String.fromCharCode(h);return f}
function _fujswclib_urlDecode(g,l){if(l)for(;0<=g.indexOf(l);)g=g.replace(l,"/");return decodeURIComponent(g)}function _fujswc_createCookie(g,l,f,k){if(f){var h=new Date;h.setTime(h.getTime()+1E3*f);f="; expires="+h.toGMTString()}else f="";g=g+"="+_fujswclib_urlEncode(l)+f+"; path=/";k&&(g+="; domain="+k);document.cookie=g}
function _fujswc_readCookie(g){var l,f,k;g+="=";l=document.cookie.split(";");for(f=0;f<l.length;++f){for(k=l[f];" "==k.charAt(0);)k=k.substring(1,k.length);if(0==k.indexOf(g)){k=k.substring(g.length,k.length);try{return decodeURIComponent(k)}catch(h){return k}}}return null}function _fujswc_eraseCookie(g){_fujswc_createCookie(g,"",-1)}
function _fujswc_request(g,l,f,k){var h=document.createElement("script"),w=new Date,n="";f=f?f:_fujswc_ac;h.type="text/javascript";n=_fujswc_url+"/t_z"+(k?k:"")+w.getTime()+"/"+f+"/";g&&(n+=g+"/");g&&l&&(n+=l);n&&(h.src=n,document.getElementsByTagName("head")[0].appendChild(h));return!0};var _fujswc_interval,_fujswc_quoteref="",_fujswc_sso=!1;
(function(){function g(a,c){_fujswc_createCookie(a.cookie,c,a.timeout,a.domain)}function l(a){_fujswc_createCookie(a.cookie,"",-1,a.domain)}function f(a){return"string"===typeof a?a:null===a||void 0===a?"":a.toString()}function k(a){return a.replace(/^[ \f\n\r\t\v\u00A0\u2028\u2029]+/,"").replace(/[ \f\n\r\t\v\u00A0\u2028\u2029]+$/,"")}function h(a){return a.replace(/[ \f\n\r\t\v\u00A0\u2028\u2029]+/g," ")}function w(a,c){function b(a){var e,f;switch(a.nodeType){case 1:e="";f=(a.tagName||"").toLowerCase();
if("script"===f||"style"===f)break;"br"===f&&c&&c.br&&(e+=c.br);for(f=0;f<a.childNodes.length;++f)e+=b(a.childNodes.item(f));return e;case 3:case 4:return a.data;case 9:return b(a.documentElement)}return""}var e;if(!a||!a.nodeType)return"";e=b(a);0===c&&(e=k(h(e)));c&&c.normws&&(e=h(e));c&&c.trim&&(e=k(e));c&&c.nows&&(e=e.replace(/[ \f\n\r\t\v\u00A0\u2028\u2029]+/g,""));return e}function n(a){var c;if(a)return P?(c=a.getAttributeNode("value"))&&c.specified?a.value:a.text:a.value}function Q(a){var c,
b,e;if(a&&a.type){switch(a.type){case "button":case "image":case "submit":case "reset":return;case "file":return;case "checkbox":if(a.checked)break;return;case "radio":if(a.checked)break;if(!a.form)return;for(c=0;c<a.form.elements.length;++c)if(b=a.form.elements.item(c),b.name===a.name&&b.checked)return b.value;return;case "select-one":return a.options&&-1!==a.selectedIndex?n(a.options.item(a.selectedIndex)):void 0;case "select-multiple":e=[];for(c=0;c<a.length;++c)b=a.item(c),b.selected&&e.push(n(b));
return e}return a.value}}function aa(a,c,b,e){return c.test(a)?a.replace(c,b):e}function q(a,c,b){for(a=a.toString(b||10);a&&a.length<c;)a="0"+a;return a}function E(a,c,b){var e=Date;var d=void 0,f,g;f=parseInt(a,10);200<f?a=f:100<f?a=1900+f:(d||(d=(new Date).getFullYear()-50),g=d%100,a=a>=g?d-g+f:100+d-g+f);var h;if(c){d={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12};switch(typeof c){case "string":(h=parseInt(c,10))&&isFinite(h)||(h=d[c.substr(0,3).toLowerCase()]);break;
case "number":h=c}c=h&&1<=h&&12>=h?h:0}else c=0;b=new e(a,c-1,parseInt(b,10));b=!b||isNaN(b.getTime())?"":b.getFullYear()+q(b.getMonth()+1,2)+q(b.getDate(),2);return b}function p(a,c){var b,e,d,f;b="January February March April May June July August September October November December".split(" ");e="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" ");if(a&&c){if("string"===typeof a)return a?(b=new Date(parseInt(a.substr(0,4),10),parseInt(a.substr(4,2),10)-1,parseInt(a.substr(6,2),
10)),b=!b||isNaN(b.getTime())?null:b):b=null,p(b,c);d="";for(f=0;f<c.length;++f)if("%"!==c.substr(f,1))d+=c.substr(f,1);else{switch(c.substr(f+1,1)){case "a":d+=e[a.getDay()].substr(0,3);break;case "A":d+=e[a.getDay()];break;case "b":case "h":d+=b[a.getMonth()].substr(0,3);break;case "B":d+=b[a.getMonth()];break;case "c":d+=a.toString();break;case "C":d+=q(a.getFullYear()/100,2);break;case "d":d+=q(a.getDate(),2);break;case "D":d+=p(a,"%m/%d/%y");break;case "e":d+=a.getDate();break;case "F":d+=p(a,
"%Y-%m-%d");break;case "H":d+=q(a.getHours(),2);break;case "I":d+=q((a.getHours()+11)%12+1,2);break;case "k":d+=a.getHours();break;case "l":d+=(a.getHours()+11)%12+1;break;case "m":d+=q(a.getMonth()+1,2);break;case "M":d+=q(a.getMinutes(),2);break;case "n":d+="\n";break;case "p":d+=12>a.getHours()?"AM":"PM";break;case "P":d+=12>a.getHours()?"am":"pm";break;case "r":d+=p(a,"%I:%M:%S %p");break;case "R":d+=p(a,"%H:%M");break;case "s":d+=a.getTime()/1E3;break;case "S":d+=q(a.getSeconds(),2);break;case "t":d+=
"\t";break;case "T":d+=p(a,"%H:%M:%S");break;case "u":d+=a.getDay()||7;break;case "w":d+=a.getDay();break;case "x":d+=p(a,"%Y-%m-%d");break;case "X":d+=p(a,"%H:%M:%S");break;case "y":d+=q(a.getFullYear()%100,2);break;case "Y":d+=a.getFullYear();break;case "z":d+=a.getTimezoneOffset();break;case "%":d+="%";break;default:d+="%"+c.substr(f,1)}++f}return d}}function R(a){return a?a.replace(/[^+0123456789*#]/g,""):""}function S(a){var c,b,e,d;c=Math.random().toString();c+="-"+(new Date).getTime();for(b=
1;b<arguments.length;++b)arguments[b]&&(c+="-"+arguments[b].toString());e=[];for(b=0;b<a;++b)e.push(0);for(b=0;b<c.length;++b)for(d=c.charCodeAt(b);0<d;d>>=8)e[b%a]^=d%256;c="";for(b=0;b<e.length;++b)c+=q(e[b],2,16);return c}function z(a,c){var b,e;b=[];for(e=c;e<a.length;++e)b.push(a[e]);return b}function m(a,c,b){var e;if(512<c.length)for(e=0;0<c.length;++e)m(a,e+"/"+c.substr(0,500),b),c=c.substr(500);else return _fujswc_request(a||_fujswc_readCookie(r.cookie)||"unknown-session","log/"+_fujswclib_urlEncode(c,
"/"),"",b||"l")}function F(a,c){var b;try{b="error/ver/"+u+"/file/"+a.fileName+"/line/"+a.lineNumber+"/type/"+a.name+"/stack/"+a.stack+"/msg/"+a.message+"/data/"+c}catch(e){b="error/ver/"+u+"/Unexpected error: "+e}return m("",b,"e")}function ba(a,c,b){var e=z(arguments,3);a&&window.clearInterval(a);return b?window.setInterval(function(){try{return b.apply(this,e)}catch(a){F(a,"Error on interval!")}},c):null}function G(a,c,b){var e=z(arguments,3);a&&window.clearTimeout(a);return b?window.setTimeout(function(){try{return b.apply(this,
e)}catch(a){F(a,"Error on timeout!")}},c):null}function H(a){var c,b;c="";for(b in a)if(void 0!==a[b]){if("."===a[b]||".."===a[b])a[b]=" "+a[b];c+="/"+_fujswclib_urlEncode(f(b),"*")+"/"+_fujswclib_urlEncode(f(a[b]),"*")}return c}function N(a){var c,b;c={};if(!a)return c;a=a.split("/");for(b=1;b<a.length;b+=2)c[_fujswclib_urlDecode(a[b],"*")]=_fujswclib_urlDecode(a[b+1],"*");return c}function T(a,c,b){var e;if(a)return D(a),e="cancel",c&&(e+="/fu_cancelreason/"+c),"sold"===c&&b&&(e+="/fu_furid/"+b),
e+="/u/"+(new Date).getTime(),_fujswc_request(a,e,"","c");m(a,"Unable to cancel session")}function U(){var a,c;if(a=document.getElementsByTagName("HEAD")[0]){for(c=a.firstChild;c;c=c.nextSibling)"SCRIPT"===c.nodeName.toUpperCase()&&c.src&&c.src.substr(0,_fujswc_url.length)===_fujswc_url&&a.removeChild(c);!(a=_fujswc_readCookie(r.cookie))||!a.length||8>a.length||(g(r,a),_fujswc_request(a,"","","h"))}}function I(a,c,b){function e(e){e||(e=window.event);e.target||(e.target=e.srcElement);try{return b.apply(this,
[e].concat(d))}catch(f){F(f,"Listening on elem "+a.id+" for "+c)}}var d=z(arguments,3);a&&(a.addEventListener?a.addEventListener(c,e,!1):a.attachEvent&&a.attachEvent("on"+c,e))}function x(a,c,b){function e(a,b){var d,e;d=a&&a.target&&a.target._fujswc_mark||b;for(e in d)if(d[e].elem)switch(d[e].value=Q(d[e].elem),d[e].elem.type){case "checkbox":case "radio":d[e].checked=d[e].elem.checked;break;case "select-one":var f=d[e],g;a:{g=d[e].elem;var h=void 0,k=void 0,l=void 0;if(g&&g.options&&(void 0===h&&
(h=Q(g)),void 0!==h))for(k=0;k<g.options.length;++k)if(l=g.options.item(k),n(l)===h){g=l.label||w(l)||l.value;break a}g=void 0}f.label=g}else d[e].value=void 0;e=z(arguments,2);return c.apply(this,[a,d].concat(e))}var d,f,g,h,k,l;d=z(arguments,3);f=function(){var b,c;b=a();for(c in b)if(!b[c].elem&&b[c].id&&(b[c].elem=document.getElementById(b[c].id)),void 0===b[c].events||void 0===b[c].events.length)b[c].events=["change"];return b}();g=[];h=[];for(k in f)if(f[k].elem){if(!f[k].elem._fujswc_mark)for(l=
0;l<f[k].events.length;++l)I.apply(this,[f[k].elem,f[k].events[l],e,f].concat(d));f[k].elem._fujswc_mark=f;g.push(k)}else f[k].optional||h.push(k);h.length&&m("","Missing elements1/ver/"+u+"/"+h.join(", "));b&&b.firenow&&e.apply(this,[null,f].concat(d));return g.length}function t(a,c){var b,e,d,h=1E3;_fujswc_quoteref&&(a.ref=_fujswc_quoteref);b=N(_fujswc_readCookie(C.cookie));b.to_wait=0;b.to_call=0;for(e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);e=H(b);g(C,e);if(0===b.annual_premium||"0"===b.annual_premium)b.annual_premium=
void 0;if(b.datasource&&(b.annual_premium||"referral"===b.datasource||"complete"===b.datasource)&&c)if(b.forename&&"not"===b.forename.toLowerCase()&&b.surname&&"real"===b.surname.toLowerCase()||/digital_ops/i.test(b.email)||/topaz/i.test(b.email)||/rbs1808.*filter.com/i.test(b.email))m("","debug/filtered1/ver/"+u),T(d,"abandoned");else{"on"===b.doNOTcall&&"complete"!==b.datasource&&(b.datasource="OptOut",b.tca_datasource="OptOut");d=/^\D*(\d+)\D*$/.exec(b.home_renew_mm);b.home_renew_mm=d&&2===d.length?
1===d[1].length?"0"+d[1]:2===d[1].length?d[1]:"00":"00";"complete"===b.datasource?(h=0,b={datasource:b.datasource,ref:b.ref||"",destday:b.destday,fu_timeoutwait:b.to_wait,fu_timeoutcall:b.to_call,fu_oldaction:"cancelcalls",fu_version:u}):"on"===b.doNOTcall||"OptOut"===b.datasource?b={datasource:"OptOut",tca_datasource:"OptOut",ref:b.ref||"",tag3:b.page,tag4:b.last_field,tag10:"on"===b.doNOTcall?"OPTOUT":"",fu_oldaction:"cancelcalls",fu_version:u}:b.destday&&"on"!==b.doNOTcall&&"OptOut"!==b.datasource&&
"referral"!==b.datasource?("1"===b.saved&&(b.datasource="savedActual",b.tca_datasource="savedActual"),b={datasource:b.datasource,tca_datasource:b.tca_datasource,ref:b.ref||"",destday:b.destday,tag:b.surname,tag2:p(b.dob,"%Y%m%d"),tag3:b.page,tag4:b.last_field,tag5:b.annual_premium,tag6:(b.car_purchased?"N":"Y")+"."+f(b.home_renew_mm),tag7:f(b.ncb_years)+"."+f(b.carcount)+"."+f(b.multicar)+"."+f(b.driverstatus),tag8:b.postcode,tag9:p(b.startdate,"%Y%m%d"),tag10:"on"===b.doNOTcall?"OPTOUT":"",info_email:b.email,
"info_AA._Title":b.title,"info_AB._Forename":b.forename,"info_AC._Surname":b.surname,"info_AD._DoB":p(b.dob,"%d%m%Y"),"info_AF._Postcode":b.postcode,"info_AG._Cover_Start":p(b.startdate,"%d/%m/%Y"),"info_AH._Annual_Premium":b.annual_premium?"\u00a3"+b.annual_premium:"","info_AI._Promo_Code":b.promo,"info_AM._Named_Driver_Title":b.nd_title,"info_AN._Named_Driver_Forename":b.nd_forename,"info_AO._Named_Driver_Surname":b.nd_surname,"info_AP._Named_Driver_DoB":p(b.nd_dob,"%d%m%Y"),"info_AQ._Named_Driver_Relationship":b.nd_relationship,
"info_AX._No._of_Cars_in_Home":f(b.carcount),"info_AY._Multi-car_Discount":b.multicar,"info_AZ._Copy_to_UIS":(b.postcode||"")+"\t"+b.surname+"\t"+b.forename+"\t"+p(b.dob,"%d%m%Y"),"info_w._Home_Renewal":b.home_renew_mmm,fu_oldaction:"cancelcalls",fu_value:b.annual_premium,fu_value_cur:b.fu_value?"GBP":void 0,fu_timeoutwait:b.to_wait,fu_timeoutcall:b.to_call,fu_version:u}):b={datasource:b.destday?b.datasource:"nophone",tca_datasource:b.destday?b.tca_datasource:"nophone",ref:b.ref||"",tag3:b.page,tag4:b.last_field,
tag10:"on"===b.doNOTcall?"OPTOUT":"",fu_oldaction:"cancelcalls",fu_version:u};e=H(b);d=_fujswc_readCookie(r.cookie);if(!d||!d.length||8>d.length)d=S(16,e);g(r,d||"");_fujswc_createCookie("opti_session",d||"");b=document.location.toString();/^(http|https):\/\/([^/]+)(:\d+)?\/.*\/ReviewandConfirm\/review/i.test(b)?D(d,e,1E3,12E4):D(d,e,h,0)}}function V(a,c){var b,e,d,h,k;d={1:"January",2:"February",3:"March",4:"April",5:"May",6:"June",7:"July",8:"August",9:"September",10:"October",11:"November",12:"December"};
b=N(_fujswc_readCookie(J.cookie));for(e in a)a.hasOwnProperty(e)&&(b[e]=a[e]);e=H(b);g(J,e);if(("0"!==b.optin_calls||"0"!==b.optin_email)&&"complete"===b.page&&c){if("1"===b.optin_calls&&"1"===b.optin_email)h="xsellCE";else if("1"===b.optin_calls)h="xsellCall";else if("1"===b.optin_email)h="xsellEmail";else return;e=N(_fujswc_readCookie(C.cookie));k=_fujswc_quoteref?_fujswc_quoteref:e.ref?e.ref:"";e=""+("1"===b.optin_calls?"Y":"N")+"."+("1"===b.optin_email?"Y":"N");var l="1"===b.optin_calls?b.destday:
"",m=b.surname,n="1"===b.home_owner?"Y":"N",q=b.home_renewal,ca="1"===b.optin_email?b.email:"",r=p(b.dob,"%Y%m%d"),t=b.postcode,v="1"===b.optin_email?b.email:"",w=b.title,x=b.forename,y=b.surname,z=b.postcode,B=b.address,A;A=parseInt(b.home_renewal,10);A=isFinite(A)?A:0;d=null===A||void 0===A?void 0:d[f(A)];b={datasource:h,ref:k,destday:l,tag:m,tag2:e,tag3:n,tag4:q,tag5:ca,tag6:r,tag8:t,info_email:v,"info_AA._Title":w,"info_AB._Forename":x,"info_AC._Surname":y,"info_AD._Postcode":z,"info_AE._Address":B,
"info_AF._Home_Renewal":d,"info_AG._Home_Owner":"1"===b.home_owner?"Y":"N","info_AH._Opt_in":e,info_DOB:p(b.dob,"%d/%m/%Y"),fu_timeoutwait:b.to_wait,fu_timeoutcall:b.to_call,fu_version:u};e=H(b);b=_fujswc_readCookie(K.cookie);if(!b||!b.length||8>b.length)b=S(16,e);g(K,b||"");D(b,e,0,0)}}function v(){var a,c;c=document.location.toString();(a=/^(http.*)\/{0,1}[?#][^\/]*$/.exec(c))&&2===a.length&&(c=a[1]);(a=/^(.*)\/$/.exec(c))&&2===a.length&&(c=a[1]);return(a=/\/([^\/]*)$/.exec(c))&&2===a.length&&(a=
a[1],(a=/(.{0,19})$/.exec(a))&&2===a.length)?a[1]:""}function W(a){var c;c=v();a=a.target.name;a=a.replace(/formField./,"");19<c.length+a.length&&(c=c.substr(0,7),a=a.substr(a.length-11,11));t({last_field:c+("."+a)},1)}function y(){var a,c;a=document.getElementsByTagName("INPUT");for(c=0;c<a.length;c++)I(a[c],"change",W);a=document.getElementsByTagName("SELECT");for(c=0;c<a.length;c++)I(a[c],"change",W)}function X(a){var c,b;if(!a)return"";c=/\s*(\S{2,4})\s*(\S{3,})\s*/.exec(a);if(!c)return"";if(3===
c.length){a=c[1].length+c[2].length;b=7-a;for(a=c[1];0<b;)a+=" ",b--;a+=c[2]}return a}function da(){y();x(function(){return{destday:{id:"formField.phone"},title:{id:"formField.details.title",optional:!0},forename:{id:"formField.details.forename"},surname:{id:"formField.details.surname"},dob_d:{id:"formField.details.birthDate.day"},dob_m:{id:"formField.details.birthDate.month"},dob_y:{id:"formField.details.birthDate.year"},email:{id:"formField.yourDetails.email"},postcode:{id:"formField.address.postcode",
optional:!0},multicar_y:{id:"formField.discount.multicar-1"},multicar_n:{id:"formField.discount.multicar-2"},carcount:{id:"formField.numberOfCarsInHome"},coverstart_d:{id:"formField.coverStartDate.day"},coverstart_m:{id:"formField.coverStartDate.month"},coverstart_y:{id:"formField.coverStartDate.year"},car_purchased:{id:"formField.vehicleNotYetPurchased"},home_renewal:{id:"formField.homeInsuranceDue"},homeowner_y:{id:"formField.ownYourHome-1"},homeowner_n:{id:"formField.ownYourHome-2"},ncb:{id:"formField.noClaimsDiscount"},
promocode:{id:"formField.details.promotionCode",optional:!0},driver2title:{id:"formField.details.title_0",optional:!0},driver2forename:{id:"formField.details.forename_0",optional:!0},driver2surname:{id:"formField.details.surname_0",optional:!0},driver2dob_d:{id:"formField.details.birthDate.day_0",optional:!0},driver2dob_m:{id:"formField.details.birthDate.month_0",optional:!0},driver2dob_y:{id:"formField.details.birthDate.year_0",optional:!0},driver2relationship:{id:"formField.details.driverRelationId",
optional:!0},driver3title:{id:"formField.details.title_1",optional:!0},driver3forename:{id:"formField.details.forename_1",optional:!0},driver3surname:{id:"formField.details.surname_1",optional:!0},driver3dob_d:{id:"formField.details.birthDate.day_1",optional:!0},driver3dob_m:{id:"formField.details.birthDate.month_1",optional:!0},driver3dob_y:{id:"formField.details.birthDate.year_1",optional:!0},driver3relationship:{id:"formField.details.driverRelationId_1",optional:!0},doNOTcall:{id:"formField.noOffersByPost_checkbox"},
doNOTcallEither:{id:"optileadConsentID",optional:!0},email_consent:{id:"formField.sendOffersByEmail_checkbox"}}},function(a,c){var b=!1,e;c.title.value&&(c.title.value=c.title.value.replace(/^\w*,/,""));c.driver2title.value&&(c.driver2title.value=c.driver2title.value.replace(/^\w*,/,""));if("Spouse"===c.driver2relationship.value||"Partner"===c.driver2relationship.value)b=!0;c.driver3title.value&&(b=!1);e=c.home_renewal&&c.home_renewal.value?c.home_renewal.value:"";var d=R(c.destday.value),h=c.email.value,
g=c.title.value,k=c.forename.value,l=c.surname.value,m=c.dob_y.value&&c.dob_m.value&&c.dob_d.value?E(c.dob_y.value,c.dob_m.value,c.dob_d.value):"",p=X(c.postcode.value),n;n=(n=document.getElementById("formField.address.packed"))&&n.value?(n=/(\w+;)(.+)/.exec(n.value))&&3===n.length?n[2]:null:null;V({page:"details",destday:d,email:h,title:g,forename:k,surname:l,dob:m,postcode:p,address:n,home_owner:c.homeowner_y.elem&&c.homeowner_y.elem.checked?"1":"0",home_renewal:e?e:"",optin_calls:c.doNOTcall&&
c.doNOTcall.elem&&!c.doNOTcall.elem.checked?"1":"0",optin_email:c.email_consent&&c.email_consent.elem&&!c.email_consent.elem.checked?"1":"0"},0);t({datasource:"quote",tca_datasource:"quoteStalled",driverstatus:c.driver3title.value?"4":b&&c.driver2title.value?"2":c.driver2title.value?"3":1,page:v(),destday:R(c.destday.value),title:c.title.value,forename:c.forename.value,surname:c.surname.value,dob:c.dob_y.value&&c.dob_m.value&&c.dob_d.value?E(c.dob_y.value,c.dob_m.value,c.dob_d.value):"",email:c.email.value,
postcode:X(c.postcode.value),multicar:c.multicar_y.checked?"Y":c.multicar_n.checked?"N":"",carcount:f(c.carcount.value),startdate:c.coverstart_y.value&&c.coverstart_m.value&&c.coverstart_d.value?E(c.coverstart_y.value,c.coverstart_m.value,c.coverstart_d.value):"",car_purchased:c.car_purchased.value,home_renew_mm:c.home_renewal.elem&&c.home_renewal.elem.selectedIndex,home_renew_mmm:c.home_renewal.value,ncb_years:c.ncb.value,nd_title:b?c.driver2title.value:"",nd_forename:b?c.driver2forename.value:"",
nd_surname:b?c.driver2surname.value:"",nd_dob:b&&c.driver2dob_y.value&&c.driver2dob_m.value&&c.driver2dob_d.value?E(c.driver2dob_y.value,c.driver2dob_m.value,c.driver2dob_d.value):"",nd_relationship:b?c.driver2relationship.value:"",promo:c.promocode.value,doNOTcall:"on"===c.doNOTcall.value||"on"===c.doNOTcallEither.value?"on":"off"},1)},{firenow:!0})}function L(){y();x(function(){},function(a,c){t({datasource:"referral",tca_datasource:"stalledReferral",page:v()},1)},{firenow:!0})}function ea(){y();
x(function(){return{calcbtn:{id:"btnRecalculateID",causesFormReplace:!0,optional:!0,events:["click"]}}},function(a,c){var b=v(),e;a:{var d,f;e=document.getElementsByClassName("your-quote");for(f=0;f<e.length;f++)if(d=e[f].getAttribute("data-annual-price")){e=d;break a}e=void 0}t({datasource:"quote",tca_datasource:"quoteStalled",page:b,annual_premium:e},1)},{firenow:!0})}function fa(){y();x(function(){var a;a=document.getElementsByTagName("BUTTON");return{btn1:{elem:2<=a.length?a[0]:null,events:["mousemove",
"focus"]},btn2:{elem:2<=a.length?a[1]:null,events:["mousemove","focus"]},btn3:{elem:3<=a.length?a[2]:null,events:["mousemove","focus"],optional:!0}}},function(a,c){t({datasource:"application",tca_datasource:"applicationStalled",page:v()},1)},{firenow:!0})}function ga(){y();x(function(){},function(a,c){t({datasource:"saved",tca_datasource:"savedStalled",to_wait:300,to_call:600,page:v()},1)},{firenow:!0})}function B(){y();x(function(){},function(a,c){t({datasource:"saved",tca_datasource:"savedStalled",
page:v()},1)},{firenow:!0})}function M(){y();x(function(){},function(a,c){t({saved:"1",datasource:"savedActual",tca_datasource:"savedActual",page:v()},1)},{firenow:!0})}function Y(){t({datasource:"complete",to_wait:"5",to_call:"5"},1);V({page:"complete",to_wait:"5",to_call:"5"},1);l(r);l(C);l(K);l(J)}function ha(){var a;a=_fujswc_readCookie(r.cookie);l(r);l(C);a&&T(a,"abandoned");m("","debug/page/referral_cancelled")}function O(){var a,c,b,e;a=document.location.toString();e=window.setInterval(function(){b=
document.location.toString();b!==a&&(clearInterval(e),O())},3E3);""!==(c=decodeURIComponent(aa(a,/^.*[?;&]fu_furid=([^;&#]*).*?$/,"$1","")))&&g(Z,c);/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\//i.test(a);/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard/i.test(a)&&(_fujswc_sso=!0);/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/aggregators\//i.test(a)?(m("","page/6/abandon"),ha()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/[gq]et-motor-quote-details-referral/i.test(a)?
(m("","page/1/referral"),L()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/[gq]et-motor-quote-details-error/i.test(a)?(m("","page/1/referral"),L()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/details\/get-motor-quote-details/i.test(a)?window.setInterval(da,2E3):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/quote\/car\/.*\/premium\/premium-error/i.test(a)?(m("","page/1/referral"),L()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/quote\/car\/.*\/premium\/premium/i.test(a)?
window.setInterval(ea,4E3):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/Summary\/confirmation/i.test(a)?(m("","page/7/thankyou"),Y()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/ReviewandConfirm\/review-referral/i.test(a)?(m("","page/1/referral"),L()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/ReviewandConfirm\/review/i.test(a)?(m("","page/2/review"),fa()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/qpm\/qpm-login-page/i.test(a)?
(m("","page/3/save"),B()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/qpm\/qpm-save-login-page/i.test(a)?(m("","page/3/save"),B()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/qpm\/qpm-registration-form/i.test(a)?(m("","page/3/save"),B()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/qpm\/qpm-forgot-password-page/i.test(a)?(m("","page/3/save"),B()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard#\/sign-in\/transfer-quote/i.test(a)?
(m("","page/4/saved"),M()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard#\/sign-in(\/register)?/i.test(a)?(m("","page/3/save"),B()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/qpm\/secure\/thank-you-for-saving/i.test(a)?(m("","page/4/saved"),M()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard#\/dashboard(\/quotes)?/i.test(a)?(m("","page/4/saved"),M()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard#\/register\/(link)|(success)/i.test(a)?
(m("","page/4/saved"),M()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/payment\/3d-secure-redirect/i.test(a)?(m("","page/5/3dsecure"),ga()):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/[^/]*\/{0,1}$/i.test(a)?(m("","page/0/homepage"),_fujswc_interval&&(window.clearInterval(_fujswc_interval),_fujswc_interval=void 0)):/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\//i.test(a)&&m("","page/8/generic")}var u,r,C,Z,K,J,P,D;u="28";
r={cookie:"fujswc_dlm",timeout:1800};C={cookie:"fujswc_dlm_data",timeout:86400};Z={cookie:"fujswc_dlm_furid",timeout:2592E3};K={cookie:"fujswc_dlm_xs",timeout:1800};J={cookie:"fujswc_dlm_data_xs",timeout:86400};P=function(){var a;return document&&document.all&&navigator&&navigator.appVersion&&null!==(a=/MSIE (\d+)\./.exec(navigator.appVersion))?parseInt(a[1],10):0}();D=function(){var a,c,b;return function(e,d,f,h){var g,k;g=new Date;if(e&&(d!==a||h&&c&&!(g.getTime()<=c.getTime()+h)))if(a=d)if(k="data"+
d+"/u/"+g.getTime(),f&&c&&g.getTime()<c.getTime()+f)b=G(b,f-(g.getTime()-c.getTime()),function(){c=new Date;b=null;_fujswc_request(e,k,"","d")});else return c=g,b=G(b),_fujswc_request(e,k,"","d");else c=null,b=G(b)}}();if(function(a){if(_fujswc_readCookie(a.cookie))return 1;g(a,"testing");if("testing"===_fujswc_readCookie(a.cookie))return l(a),1;l(a);return 0}(r)&&!_fujswc_interval)if(_fujswc_interval=ba(_fujswc_interval,1E4,U),G(0,1E3,U),"complete"===document.readyState||"interactive"===document.readyState)try{O()}catch(ia){F(ia,
"Running examinepage()")}else I(window,"load",O),/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/.*\/Summary\/confirmation/i.test(document.location.toString())&&(m("","page/7/thankyou"),Y())})();
_fujswc_sso||/^(http|https):\/\/(www.directline.com|[^/]+.directline.com)(:\d+)?\/my-dashboard/i.test(document.location.toString())||function(g){function l(f){(f=g.extend({},f.pageData||{}))&&f.quoteRef&&(_fujswc_quoteref=f.quoteRef)}g("body");Cog.addListener("elements.stateProvider","stateChanged",function(f){if(f=f.eventData)f=g.proxy(l,null,f.state||{}),Cog.addListener("elements.stateProvider","allElementsUpdated",f,{disposable:!0})},{disposable:!1})}(COGjQuery);function _fujswc_start(){};
